USE mysql;

DROP FUNCTION IF EXISTS bound;
DROP FUNCTION IF EXISTS bround;
DROP FUNCTION IF EXISTS corr;
DROP FUNCTION IF EXISTS covariance;
DROP FUNCTION IF EXISTS cut;
DROP FUNCTION IF EXISTS fnv;
DROP FUNCTION IF EXISTS getint;
DROP FUNCTION IF EXISTS group_first;
DROP FUNCTION IF EXISTS group_last;
DROP FUNCTION IF EXISTS invbit;
DROP FUNCTION IF EXISTS isbit;
DROP FUNCTION IF EXISTS kurtosis;
DROP FUNCTION IF EXISTS lessavg;
DROP FUNCTION IF EXISTS lesspartpct;
DROP FUNCTION IF EXISTS lesspart;
DROP FUNCTION IF EXISTS median;
DROP FUNCTION IF EXISTS stats_mode;
DROP FUNCTION IF EXISTS ngram;
DROP FUNCTION IF EXISTS noverk;
DROP FUNCTION IF EXISTS percentile_cont;
DROP FUNCTION IF EXISTS percentile_disc;
DROP FUNCTION IF EXISTS rotbit;
DROP FUNCTION IF EXISTS rotint;
DROP FUNCTION IF EXISTS rsumd;
DROP FUNCTION IF EXISTS rsumi;
DROP FUNCTION IF EXISTS setbit;
DROP FUNCTION IF EXISTS setint;
DROP FUNCTION IF EXISTS skewness;
DROP FUNCTION IF EXISTS slug;
DROP FUNCTION IF EXISTS xround;

CREATE FUNCTION bound RETURNS real SONAME 'udf_infusion.dll';
CREATE FUNCTION bround RETURNS real SONAME 'udf_infusion.dll';
CREATE AGGREGATE FUNCTION corr RETURNS real SONAME 'udf_infusion.dll';
CREATE AGGREGATE FUNCTION covariance RETURNS real SONAME 'udf_infusion.dll';
CREATE FUNCTION cut RETURNS string SONAME 'udf_infusion.dll';
CREATE FUNCTION fnv RETURNS integer SONAME 'udf_infusion.dll';
CREATE FUNCTION getint RETURNS integer SONAME 'udf_infusion.dll';
CREATE AGGREGATE FUNCTION group_first RETURNS string SONAME 'udf_infusion.dll';
CREATE AGGREGATE FUNCTION group_last RETURNS string SONAME 'udf_infusion.dll';
CREATE FUNCTION invbit RETURNS integer SONAME 'udf_infusion.dll';
CREATE FUNCTION isbit RETURNS integer SONAME 'udf_infusion.dll';
CREATE AGGREGATE FUNCTION kurtosis RETURNS real SONAME 'udf_infusion.dll';
CREATE AGGREGATE FUNCTION lessavg RETURNS integer SONAME 'udf_infusion.dll';
CREATE AGGREGATE FUNCTION lesspartpct RETURNS integer SONAME 'udf_infusion.dll';
CREATE AGGREGATE FUNCTION lesspart RETURNS integer SONAME 'udf_infusion.dll';
CREATE AGGREGATE FUNCTION median RETURNS real SONAME 'udf_infusion.dll';
CREATE AGGREGATE FUNCTION stats_mode RETURNS real SONAME 'udf_infusion.dll';
CREATE FUNCTION ngram RETURNS string SONAME 'udf_infusion.dll';
CREATE FUNCTION noverk RETURNS integer SONAME 'udf_infusion.dll';
CREATE AGGREGATE FUNCTION percentile_cont RETURNS real SONAME 'udf_infusion.dll';
CREATE AGGREGATE FUNCTION percentile_disc RETURNS real SONAME 'udf_infusion.dll';
CREATE FUNCTION rotbit RETURNS integer SONAME 'udf_infusion.dll';
CREATE FUNCTION rotint RETURNS integer SONAME 'udf_infusion.dll';
CREATE FUNCTION rsumd RETURNS real SONAME 'udf_infusion.dll';
CREATE FUNCTION rsumi RETURNS integer SONAME 'udf_infusion.dll';
CREATE FUNCTION setbit RETURNS integer SONAME 'udf_infusion.dll';
CREATE FUNCTION setint RETURNS integer SONAME 'udf_infusion.dll';
CREATE AGGREGATE FUNCTION skewness RETURNS real SONAME 'udf_infusion.dll';
CREATE FUNCTION slug RETURNS string SONAME 'udf_infusion.dll';
CREATE FUNCTION xround RETURNS integer SONAME 'udf_infusion.dll';
